# -*- coding: utf-8 -*-
"""Copy of nsrdata.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZMINbHB9eEQf4nGzwHxdM28_v1TJ8m_i
"""

print("hello")

print("this is to check azure function")

